# @format

apiVersion: v1
kind: Service
metadata:
  name: checkday-public-load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:467465390813:certificate/4a3b1c6c-ba61-41fc-9e66-bd4697b7d41b"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-redirect: "443"
spec:
  type: LoadBalancer
  selector:
    app: checkday-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5969
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5969
